version: '3'
services:
  backend:
    build: ./courses_api
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./courses-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
